import Head from "next/head";
import Image from "next/image";
import axios from 'axios';
import Link from 'next/link'
import { Inter } from "next/font/google";
import styles from "@/styles/mainpage.module.css";
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ["latin"] });
axios.defaults.baseURL = "https://peij7sabwv.ap-northeast-1.awsapprunner.com";
axios.defaults.responseType = "json"

export default function Home() {
  // const [data, setData] = useState([]);

  // useEffect(() => {
  //   const fetchData = async () => {
  //     try {
  //       const response = await axios.get('/');
  //       setData(response.data.vod_thumnail);
  //     } catch (error) {
  //       console.error('Error fetching data:', error);
  //     }
  //   };
  //   fetchData();
  // }, []);

  return (
    <>
      <Head>
        <title>OTT 서비스</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          {/* 상단 네비게이션바 */}
          <nav className={styles.navbar}>
            <div className={styles.navbarBrand}>
              <Link href="/">OTT 서비스</Link>
            </div>
          </nav>

          {/* 메인 콘텐츠 */}
          <main className={styles.mainContent}>
            <section className={styles.hero}>
              <h1>Test Title</h1>
              <p>Test SubTitle</p>
            </section>
            <section className={styles.featured}>
              <section className={styles.sync}>
                <h2>영화</h2>
                <div>
                  <Link href="/g1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/movie/vod/g1/THUMB/g1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>그레이하운드</p>
                  </Link>
                  <Link href="/e1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/movie/vod/e1/THUMB/e1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>2012</p>
                  </Link>
                  <Link href="/m1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/movie/vod/m1/THUMB/m1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>미드웨이</p>
                  </Link>
                  <Link href="/gang1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/movie/vod/gang1/THUMB/gang1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>강릉</p>
                  </Link>
                </div>

                <h2>드라마</h2>
                <div>
                  <Link href="/go1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/drama/vod/go1/THUMB/go1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>고려거란전쟁</p>
                  </Link>
                  <Link href="/du1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/drama/vod/du1/THUMB/du1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>두뇌공조</p>
                  </Link>
                  <Link href="/zin1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/drama/vod/zin1/THUMB/zin1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>진검승부</p>
                  </Link>
                  <Link href="/chun1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/drama/vod/chun1/THUMB/chun1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>천명</p>
                  </Link>
                </div>

                <h2>예능</h2>
                <div>
                  <Link href="/nol1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/enter/vod/nol1/THUMB/nol1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>놀면 뭐하니</p>
                  </Link>
                  <Link href="/na1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/enter/vod/na1/THUMB/na1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>나 혼자 산다</p>
                  </Link>
                  <Link href="/mu1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/enter/vod/mu1/THUMB/mu1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>무한도전</p>
                  </Link>
                  <Link href="/shin1">
                    <img src='https://vodasiabuk.s3.ap-northeast-2.amazonaws.com/enter/vod/shin1/THUMB/shin1.0000000.jpg' alt="@public/favicon.ico" width="240" height="135" />
                    <p>신서유기</p>
                  </Link>
                </div>
              </section>
            </section>
          </main>
        </div>
      </main>
    </>
  );
}
